name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: samihann/metricsFork@master
        name: Full-year calendar
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar_duration: full-year
          base: ""
          plugin_isocalendar: yes
  github-metrics-2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: samihann/metricsFork@master
        name: Language
        with:
          filename: metrics.plugin.language.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
